### ISSUE TITLE
Docker-from-Docker (Windows) Docker Compose EXTRA string=

### ISSUE THREAD

**Issue by mikemcnut** [devcontainers/features#391]
The latest version of docker-from-docker breaks ${LOCAL_WORKSPACE_FOLDER} bind volumes. 

devcontainer.json configuration:

```json
"features": {
        "ghcr.io/devcontainers/features/docker-from-docker:1": {}
    },
```
docker-compose volume configuration:
```yaml
volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER}/<rest-of-path>
        target: /root/<rest-of-path>
```

docker-compose up results in
Resulting error:
`Error response from daemon: /workspaces/<path-to-workspace>/c:\Users<Path-to-folder>%!(EXTRA string=is not a valid Windows path)`

Without changing the docker-compose file and simply changing the docker-from-docker to:
```json
"features": {
        "ghcr.io/devcontainers/features/docker-from-docker:1.0.8": {
            "moby": false,
            "version": "5:20.10.22~3-0~ubuntu-focal"
},
```

results in successful builds. 

This may be a bug with the moby image. Please advise.
