### ISSUE TITLE
`docker-outside-of-docker` feature does not work with docker-compose

### ISSUE THREAD

**Issue by felipecrs** [devcontainers/features#444]
I created a minimal, reproducible example: https://github.com/felipecrs/test-devcontainer-docker-feature

It works when not using docker compose, but doesn't work when using docker compose. Apparently, the entrypoint exits early in that case.

https://user-images.githubusercontent.com/29582865/217395257-f5526061-d3e6-47f0-8f39-fb939e205d84.mp4

**Comment by samruddhikhandale** [comment]
Hi 👋 

I was able to make your dev config work with some changes 👇 

devcontainer.json
```jsonc 
{
	"name": "Ubuntu",
	"dockerComposeFile": "docker-compose.yaml",
  	"service": "devcontainer",
	"features": {
		"ghcr.io/devcontainers/features/docker-outside-of-docker:1": {}
	},
	"workspaceFolder": "/workspaces/${localWorkspaceFolderBasename}"
}

```

docker-compose.yaml
```
version: '3'

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:jammy
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 
```

Both the files are inside the `.devcontainer` folder.

![image](https://user-images.githubusercontent.com/24955913/217948435-818b0d4c-063c-41ee-acad-60a3b3b1b252.png)

Looks good to me 👇 

![image](https://user-images.githubusercontent.com/24955913/217948508-07cd1a9f-77cd-4b51-9216-18149ef7a7a6.png)

@felipecrs can you make these updates and retry? 

Ref: https://github.com/devcontainers/templates/tree/main/src/docker-outside-of-docker-compose Template, feel free to take a look at it.
