### ISSUE TITLE
[sshd] ignored `SSHD_PORT`

### ISSUE THREAD

**Issue by Esgariot** [devcontainers/features#564]
First-time run, while using docker-compose and devcontainer feature sshd, with `SSHD_PORT` set to 22 was ignored, despite being later present in `/etc/environment` on container it was installed in.

devcontainer.json:

```json
{
  "name": "<omitted>",
  "workspaceFolder": "/workspace",
  "dockerComposeFile": [
    "docker-compose.yaml",
    "docker-compose.local.yaml"
  ],
  "updateRemoteUserUID": false,
  "remoteUser": "user",
  "service": "dev",
  "features": {
    "ghcr.io/devcontainers-contrib/features/fzf:1": {},
    "ghcr.io/devcontainers/features/github-cli": {},
    "ghcr.io/devcontainers/features/sshd": {},
    "ghcr.io/devcontainers-contrib/features/exa:1": {}
  },
  "containerEnv": {
    "SSHD_PORT": "22"
  }
}
```
nothing in regards to `SSHD_PORT` anywhere else in config. `/etc/ssh/sshd_config` in container contains explicit `Port 2222`, so it was modified by `install.sh`, but port environment variable was not present at the time somehow.

vscode log excerpt:

```
[118257 ms] Docker Compose override file for creating container:
version: '3.2'

services:
  'dev':
    entrypoint: ["/bin/sh", "-c", "echo Container started\n
trap \"exit 0\" 15\n
/usr/local/share/ssh-init.sh\n
exec \"$$@\"\n
while sleep 1 & wait $$!; do :; done", "-"]
    environment:
      - SSHD_PORT=22
    labels:
      - 'devcontainer.local_folder=<omitted>
      - 'devcontainer.config_file=<omitted>/devcontainer.json'
    volumes:
      - vscode:/vscode
volumes:
  vscode:
    external: true
```

Where else could I specify `SSHD_PORT` variable?
